variable "awslogs_group" {}
variable "container_definition_file" {}
variable "host_port" {}
variable "container_port" {}
variable "memory" {}
variable "image" {}
variable "container_name" {}
variable "name" {}
variable "task_role_arn" {}
variable "environment" {}
variable "cpu" {}
variable "desired_count" {}
variable "cluster_name" {}
variable "target_group_arn" {}
variable "bloom_environment" {}
variable "ecr_url" {}
variable "aws_region" {}
variable "ecs_service_role" {}
variable "alb_tg" {}
variable "alb_listener_rule" {}
variable "alb_listener" {}